name: continuous-integration-workflow.yml

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get and run the base moj spark local Docker image for testing
      run:  docker run --rm  mamonu/moj-spark-jovyan:baseenv /bin/bash -c "cd v1  && pytest -v"
    
